spring:
  mail:
    password: bsjymoixsiwadche
    username: 2740860037@qq.com
    default-encoding: UTF-8
    host: smtp.qq.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot3-vue3?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/**.xml